name: Hardcoded Secret 

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script with secret
        run: |
          echo "Using hardcoded secret: my-very-secret-api-key-123456"
